# Generated by Django 3.0.5 on 2020-08-08 16:35

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatarcategory',
            name='sort',
            field=models.CharField(choices=[('user', 'Пользовательский'), ('role', 'Для ролевой')], default='user',
                                   max_length=10, verbose_name='Тип аватара'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='faction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Faction',
                                    verbose_name='Faction'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to_mugshot,
                                    verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='rpl_avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='users.Avatar', verbose_name='avatar'),
        ),
        migrations.DeleteModel(
            name='RplAvatar',
        ),
        migrations.DeleteModel(
            name='RplAvatarCategory',
        ),
    ]
