# Generated by Django 3.0.5 on 2020-05-17 22:51

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprofiles',
            name='birthday_dayofyear_internal',
        ),
        migrations.AddField(
            model_name='usersprofiles',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 1, 6), verbose_name='birthday'),
        ),
    ]
