# Generated by Django 3.0.5 on 2020-05-19 21:05

import ckeditor.fields
import django.db.models.deletion
import image_cropping.fields
import multiselectfield.db.fields
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
        ('users', '0002_auto_20200518_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofiles',
            name='geo_permissions',
            field=models.CharField(choices=[('show_all', 'Show all data about your location in your profile '), (
            'show_no_details', 'Show only data about your country and city, but without details'),
                                            ('show_country', 'Show only data about your country in your profile'),
                                            ('show_city', 'Show only data about your city in your profile'),
                                            ('show_none', "Doesn't show information about my position in profile")],
                                   default='show_no_details', max_length=200, verbose_name='Location permissions'),
        ),
        migrations.AddField(
            model_name='usersprofiles',
            name='level',
            field=models.IntegerField(default=0, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='usersprofiles',
            name='permissions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('faction', 'Faction'),
                                                                                   ('speciality', 'Faction'),
                                                                                   ('first_visit', 'First visit'),
                                                                                   ('last_visit', 'Last visit'),
                                                                                   ('birthday', 'Birthday'),
                                                                                   ('gender', 'Gender'),
                                                                                   ('reputation', 'Reputation'),
                                                                                   ('money', 'Money'),
                                                                                   ('xp', 'Experience'),
                                                                                   ('lvl', 'Level'), ('rank', 'Rank')],
                                                              max_length=200, null=True, verbose_name='права'),
        ),
        migrations.AddField(
            model_name='usersprofiles',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='rank'),
        ),
        migrations.AddField(
            model_name='usersprofiles',
            name='rpl_lvl',
            field=models.IntegerField(default=0, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='usersprofiles',
            name='rpl_nickname',
            field=models.CharField(blank=True, default='Stalker', max_length=50, verbose_name='Nickname of hero'),
        ),
        migrations.AddField(
            model_name='usersprofiles',
            name='rpl_xp',
            field=models.IntegerField(default=0, verbose_name='experience'),
        ),
        migrations.AddField(
            model_name='usersprofiles',
            name='speciality',
            field=models.CharField(choices=[('no', 'Without speciality'), ('hunter', 'Hunter'), ('warrior', 'Warrior'),
                                            ('stalker', 'Stalker'), ('mechanic', 'Mechanic'), ('doctor', 'Doctor'),
                                            ('trader', 'Trader'), ('guide', 'Guide')], default='no', max_length=200,
                                   verbose_name='Speciality'),
        ),
        migrations.AddField(
            model_name='usersprofiles',
            name='xp',
            field=models.IntegerField(default=0, verbose_name='experience'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='cities_light.City'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='cities_light.Country'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='mugshot',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=users.models.upload_to_mugshot,
                                                       verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='rpl_avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='users.RplAvatar', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='rpl_bio',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='biography'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='rpl_first_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='First name of hero'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='rpl_second_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Second name of hero'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='sign_image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=users.models.upload_to_mugshot,
                                                       verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='signature',
            field=ckeditor.fields.RichTextField(default='', verbose_name='signature'),
        ),
    ]
