# Generated by Django 3.0.5 on 2020-08-12 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20200808_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='logo',
            field=models.FileField(blank=True, default='postap.png', help_text='Форматы svg, png, gif',
                                   upload_to='users/factions',
                                   validators=[django.core.validators.FileExtensionValidator(['png', 'gif', 'svg'])],
                                   verbose_name='Логотип'),
        ),
    ]
