# Generated by Django 3.0.5 on 2020-12-05 19:29

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20200812_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprofiles',
            name='mugshot',
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='avatar',
            field=models.ImageField(blank=True, default='postap.png', null=True,
                                    upload_to=users.models.upload_to_avatar, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='sign_image',
            field=models.ImageField(blank=True, default='postap.png', null=True, upload_to=users.models.upload_to_sign,
                                    verbose_name='Signature image'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to_bg,
                                    verbose_name='Background image'),
        ),
    ]
