# Generated by Django 3.0.5 on 2020-05-20 21:36

import datetime

import ckeditor.fields
import django.db.models.deletion
import image_cropping.fields
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20200520_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofiles',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 1, 6), verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('Cropping avatar', '80x80', adapt_rotation=False,
                                                        allow_fullsize=False, free_crop=False, help_text=None,
                                                        hide_image_field=False, size_warning=False,
                                                        verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='faction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Faction',
                                    verbose_name='Faction'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='None', max_length=100,
                                   verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='level',
            field=models.IntegerField(default=0, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='money',
            field=models.IntegerField(default=0, verbose_name='Money'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='mugshot',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=users.models.upload_to_mugshot,
                                                       verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='Rank of hero'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='reputation',
            field=models.IntegerField(default=0, verbose_name='Reputation'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='rpl_bio',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Biography of hero'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='rpl_lvl',
            field=models.IntegerField(default=0, verbose_name='Level of hero'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='rpl_xp',
            field=models.IntegerField(default=0, verbose_name='Experience of hero'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='sign_image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=users.models.upload_to_mugshot,
                                                       verbose_name='Avatar of hero'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='sign_image_crop',
            field=image_cropping.fields.ImageRatioField('Cropping avatar', '600x200', adapt_rotation=False,
                                                        allow_fullsize=False, free_crop=False, help_text=None,
                                                        hide_image_field=False, size_warning=False,
                                                        verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='signature',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='speciality',
            field=models.CharField(choices=[('no', 'Without speciality'), ('hunter', 'Hunter'), ('warrior', 'Warrior'),
                                            ('stalker', 'Stalker'), ('mechanic', 'Mechanic'), ('doctor', 'Doctor'),
                                            ('trader', 'Trader'), ('guide', 'Guide')], default='no', max_length=200,
                                   verbose_name='Speciality of hero'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='xp',
            field=models.IntegerField(default=0, verbose_name='Experience'),
        ),
    ]
