# Generated by Django 3.0.5 on 2021-01-07 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('equipment', '0012_auto_20210107_1055'),
        ('users', '0004_auto_20201205_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteuser',
            options={'verbose_name': 'Снаряжение', 'verbose_name_plural': 'Снаряжения'},
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='equipment',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='armor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='armor', to='equipment.EquipItem', verbose_name='Броня'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='backpack',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='backpack', to='equipment.EquipItem', verbose_name='Устройство №1'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='belt1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='ammo1', to='equipment.EquipItem', verbose_name='Боеприпасы №1'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='belt2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='ammo2', to='equipment.EquipItem', verbose_name='Боеприпасы №2'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='belt3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='ammo3', to='equipment.EquipItem', verbose_name='Боеприпасы №3'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='belt4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='ammo4', to='equipment.EquipItem', verbose_name='Боеприпасы №4'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='container1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='art1', to='equipment.EquipItem', verbose_name='Артефакт №1'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='container2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='art2', to='equipment.EquipItem', verbose_name='Артефакт №2'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='container3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='art3', to='equipment.EquipItem', verbose_name='Артефакт №3'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='container4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='art4', to='equipment.EquipItem', verbose_name='Артефакт №4'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='container5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='art5', to='equipment.EquipItem', verbose_name='Артефакт №5'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='device1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='device1', to='equipment.EquipItem', verbose_name='Устройство №1'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='device2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='device2', to='equipment.EquipItem', verbose_name='Устройство №2'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='device3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='device3', to='equipment.EquipItem', verbose_name='Устройство №3'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='helmet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='helmet', to='equipment.EquipItem', verbose_name='Шлем'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='slot1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='weapons1', to='equipment.EquipItem', verbose_name='Первый слот'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='slot2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='weapons2', to='equipment.EquipItem', verbose_name='Второй слот'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='slot3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='weapons3', to='equipment.EquipItem', verbose_name='Третий слот'),
        ),
    ]
