# Generated by Django 3.0.5 on 2020-05-21 22:31

import django.db.models.deletion
import smart_selects.db_fields
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
        ('users', '0004_auto_20200521_0036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name': 'Аватар', 'verbose_name_plural': 'Аватары'},
        ),
        migrations.AlterModelOptions(
            name='avatarcategory',
            options={'verbose_name': 'Категория аватаров', 'verbose_name_plural': 'Категории аватаров'},
        ),
        migrations.AlterModelOptions(
            name='faction',
            options={'verbose_name': 'Группировка', 'verbose_name_plural': 'Группировки'},
        ),
        migrations.AlterModelOptions(
            name='rplavatar',
            options={'verbose_name': 'Аватар персонажа', 'verbose_name_plural': 'Аватары персонажей'},
        ),
        migrations.AlterModelOptions(
            name='rplavatarcategory',
            options={'verbose_name': 'Категория аватаров персонажей',
                     'verbose_name_plural': 'Категории аватаров персонажей'},
        ),
        migrations.AlterField(
            model_name='faction',
            name='logo',
            field=stdimage.models.StdImageField(blank=True, default='postap.png', upload_to='users/factions',
                                                verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='name',
                                                            chained_model_field='name', null=True,
                                                            on_delete=django.db.models.deletion.DO_NOTHING,
                                                            to='cities_light.City'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='country',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='name',
                                                            chained_model_field='name', null=True,
                                                            on_delete=django.db.models.deletion.DO_NOTHING,
                                                            to='cities_light.Country'),
        ),
    ]
