# Generated by Django 3.0.5 on 2021-01-07 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_auto_20210107_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
