# Generated by Django 3.0.5 on 2020-05-21 22:36

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
        ('users', '0005_auto_20200522_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofiles',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='continent',
                                                            chained_model_field='continent', null=True,
                                                            on_delete=django.db.models.deletion.DO_NOTHING,
                                                            to='cities_light.City'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='country',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='continent',
                                                            chained_model_field='continent', null=True,
                                                            on_delete=django.db.models.deletion.DO_NOTHING,
                                                            to='cities_light.Country'),
        ),
    ]
