# Generated by Django 3.0.5 on 2021-02-15 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_auto_20210107_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='rpl_avatar',
            field=models.ForeignKey(blank=True, default='img/profile/no_data.gif', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='users.Avatar',
                                    verbose_name='avatar'),
        ),
    ]
