# Generated by Django 3.0.5 on 2020-05-23 21:55

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_auto_20200522_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofiles',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('Cropping avatar', '150x150', adapt_rotation=False,
                                                        allow_fullsize=False, free_crop=False, help_text=None,
                                                        hide_image_field=False, size_warning=False,
                                                        verbose_name='cropping'),
        ),
    ]
