# Generated by Django 3.0.5 on 2020-05-23 21:58

import image_cropping.fields
import users.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_auto_20200524_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofiles',
            name='sign_image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=users.models.upload_to_mugshot,
                                                       verbose_name='Signature image'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='sign_image_crop',
            field=image_cropping.fields.ImageRatioField('Cropping image', '600x200', adapt_rotation=False,
                                                        allow_fullsize=False, free_crop=False, help_text=None,
                                                        hide_image_field=False, size_warning=False,
                                                        verbose_name='cropping'),
        ),
    ]
