# Generated by Django 3.0.5 on 2020-05-23 22:00

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0009_auto_20200524_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofiles',
            name='sign_image_crop',
            field=image_cropping.fields.ImageRatioField('Cropping image', '600x200', adapt_rotation=False,
                                                        allow_fullsize=False, free_crop=False, help_text=None,
                                                        hide_image_field=False, size_warning=False,
                                                        verbose_name='sign image crop'),
        ),
    ]
