# Generated by Django 3.0.5 on 2021-03-12 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0009_auto_20210216_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='rpl_avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='users.Avatar', verbose_name='avatar'),
        ),
    ]
