# Generated by Django 3.0.5 on 2020-05-26 20:01

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0017_auto_20200526_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofiles',
            name='sign_image_crop',
            field=image_cropping.fields.ImageRatioField('sign_image', '600x200', adapt_rotation=False,
                                                        allow_fullsize=False, free_crop=False, help_text=None,
                                                        hide_image_field=False, size_warning=False,
                                                        verbose_name='Cropping image'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=300, null=True, unique=True,
                                   verbose_name='Слаг'),
        ),
    ]
