# Generated by Django 3.0.5 on 2020-05-26 21:45

import stdimage.models
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0018_auto_20200526_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='cropping',
        ),
        migrations.RemoveField(
            model_name='rplavatar',
            name='cropping',
        ),
        migrations.RemoveField(
            model_name='usersprofiles',
            name='cropping',
        ),
        migrations.RemoveField(
            model_name='usersprofiles',
            name='sign_image_crop',
        ),
        migrations.AddField(
            model_name='usersprofiles',
            name='mugshot_full',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=users.models.upload_to_mugshot,
                                                verbose_name='Full avatar'),
        ),
        migrations.AddField(
            model_name='usersprofiles',
            name='sign_image_full',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=users.models.upload_to_mugshot,
                                                verbose_name='Signature image full'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, upload_to='avatars/base', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='rplavatar',
            name='image',
            field=models.ImageField(blank=True, upload_to='avatars/base', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='mugshot',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=users.models.upload_to_mugshot,
                                                verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='sign_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to_mugshot,
                                    verbose_name='Signature image'),
        ),
    ]
