# Generated by Django 3.0.5 on 2020-05-27 21:33

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0020_auto_20200528_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprofiles',
            name='mugshot_full',
        ),
        migrations.RemoveField(
            model_name='usersprofiles',
            name='sign_image_full',
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='mugshot',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to_mugshot,
                                    verbose_name='Avatar'),
        ),
    ]
