# Generated by Django 3.0.5 on 2020-05-30 20:52

import stdimage.models
import users.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0021_auto_20200528_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofiles',
            name='mugshot',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=users.models.upload_to_mugshot,
                                                verbose_name='Avatar'),
        ),
    ]
