# Generated by Django 3.0.5 on 2020-05-31 18:20

import stdimage.models
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0022_auto_20200530_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprofiles',
            name='geo_permissions',
        ),
        migrations.AddField(
            model_name='usersprofiles',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to_bg,
                                    verbose_name='Signature image'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='mugshot',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=users.models.upload_to_avatar,
                                                verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='sign_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to_sign,
                                    verbose_name='Signature image'),
        ),
    ]
