# Generated by Django 3.0.5 on 2020-06-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0023_auto_20200531_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofiles',
            name='quote',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Status'),
        ),
    ]
