# Generated by Django 3.0.5 on 2020-07-28 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('equipment', '0001_initial'),
        ('users', '0025_auto_20200616_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofiles',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='equipment.Equip'),
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
