# Generated by Django 3.0.5 on 2020-04-26 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallerys',
            },
        ),
        migrations.CreateModel(
            name='GalleriedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='gallery_gallerieditem_galleried_items',
                                                   to='contenttypes.ContentType', verbose_name='Content type')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='gallery_gallerieditem_items', to='gallery.Gallery')),
            ],
            options={
                'verbose_name': 'Galleried Item',
                'verbose_name_plural': 'Galleried Items',
                'unique_together': {('content_type', 'object_id', 'gallery')},
                'index_together': {('content_type', 'object_id')},
            },
        ),
    ]
