# Generated by Django 3.0.5 on 2020-04-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerieditem',
            name='image',
            field=models.ImageField(default='goose.jpg', upload_to='test'),
        ),
        migrations.AlterUniqueTogether(
            name='gallerieditem',
            unique_together={('image', 'object_id', 'gallery')},
        ),
        migrations.AlterIndexTogether(
            name='gallerieditem',
            index_together={('image', 'object_id')},
        ),
        migrations.RemoveField(
            model_name='gallerieditem',
            name='content_type',
        ),
    ]
