# Generated by Django 3.0.5 on 2020-04-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gallery', '0004_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOne',
            fields=[
                ('someprefix1_title', models.CharField(blank=True, default='', max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='test',
            name='gallery',
        ),
    ]
