# Generated by Django 3.0.5 on 2020-04-26 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gallery', '0005_auto_20200426_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.ModelOne'),
        ),
    ]
