# Generated by Django 3.0.5 on 2020-04-26 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gallery', '0006_test_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='test',
            name='gallery',
        ),
        migrations.AddField(
            model_name='gallery',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Test'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='goose.jpg', upload_to='test'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GalleriedItem',
        ),
        migrations.DeleteModel(
            name='ModelOne',
        ),
    ]
