# Generated by Django 3.0.5 on 2020-04-26 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gallery', '0007_auto_20200426_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='entry',
            new_name='field',
        ),
        migrations.AddField(
            model_name='test',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Test'),
        ),
    ]
