# Generated by Django 3.0.5 on 2020-04-26 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gallery', '0008_auto_20200426_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='field',
            new_name='entry',
        ),
        migrations.RemoveField(
            model_name='test',
            name='entry',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Test'),
        ),
    ]
