# Generated by Django 3.0.5 on 2020-04-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gallery', '0010_auto_20200427_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='name',
        ),
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(default='PIZDEC', max_length=200),
            preserve_default=False,
        ),
    ]
