# Generated by Django 3.0.5 on 2020-04-26 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20200427_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
    ]
