# Generated by Django 3.0.5 on 2020-05-14 21:26

import gallery.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gallery', '0015_auto_20200514_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='descript',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='title',
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=stdimage.models.StdImageField(upload_to=gallery.models.upload_to),
        ),
    ]
