# Generated by Django 3.0.5 on 2020-05-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gallery', '0016_auto_20200515_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='descript',
            field=models.CharField(default='', max_length=1000, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок'),
        ),
    ]
