# Generated by Django 3.0.5 on 2020-05-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gallery', '0017_auto_20200515_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='descript',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок'),
        ),
    ]
