# Generated by Django 3.0.5 on 2020-05-28 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gallery', '0019_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
