# Generated by Django 3.0.5 on 2020-12-05 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('equipment', '0003_auto_20201205_2139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodAndMedical',
            new_name='FoodAndMedicine',
        ),
        migrations.AlterField(
            model_name='equipitem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'equipment'), ('model', 'ammo')),
                                                              models.Q(('app_label', 'equipment'), ('model', 'addon')),
                                                              models.Q(('app_label', 'equipment'), ('model', 'weapon')),
                                                              models.Q(('app_label', 'equipment'), ('model', 'outfit')),
                                                              models.Q(('app_label', 'equipment'), ('model', 'helmet')),
                                                              models.Q(('app_label', 'equipment'),
                                                                       ('model', 'backpack')),
                                                              models.Q(('app_label', 'equipment'), ('model', 'device')),
                                                              models.Q(('app_label', 'equipment'),
                                                                       ('model', 'foodandmedicine')),
                                                              models.Q(('app_label', 'equipment'), ('model', 'misc')),
                                                              models.Q(('app_label', 'equipment'),
                                                                       ('model', 'artifact')),
                                                              models.Q(('app_label', 'equipment'),
                                                                       ('model', 'questitem')), _connector='OR'),
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType',
                                    verbose_name='Тип предмета'),
        ),
    ]
