# Generated by Django 3.0.5 on 2020-12-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('equipment', '0004_auto_20201205_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='mass',
            field=models.FloatField(default=0, verbose_name='Масса'),
        ),
    ]
