# Generated by Django 3.0.5 on 2020-12-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('equipment', '0005_auto_20201205_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='equipped_icon',
            field=models.ImageField(default='postap.png', upload_to='', verbose_name='Иконка персонажа в костюме'),
        ),
    ]
