# Generated by Django 3.0.5 on 2020-12-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('equipment', '0006_outfit_equipped_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='sort',
            field=models.CharField(
                choices=[('rock', 'Булыжник'), ('first', 'I уровня'), ('second', 'IІ уровня'), ('third', 'IІІ уровня'),
                         ('empty', 'Пустышка')], default='rock', max_length=100, verbose_name='Тип артефакта'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='ammo_type',
            field=models.ManyToManyField(help_text='Боеприпасы которые используются данным видом оружия',
                                         related_name='ammo_type', to='equipment.Ammo',
                                         verbose_name='Тип боепприпасов'),
        ),
    ]
