# Generated by Django 3.0.5 on 2020-12-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('equipment', '0007_auto_20201206_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='addon1',
            field=models.ManyToManyField(blank=True, help_text='Возможные аддоны для первого слота аддонов', null=True,
                                         related_name='addon1', to='equipment.Addon',
                                         verbose_name='1 слот аддонов: Варианты'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='addon2',
            field=models.ManyToManyField(blank=True, help_text='Возможные аддоны для первого слота аддонов', null=True,
                                         related_name='addon2', to='equipment.Addon',
                                         verbose_name='2 слот аддонов: Варианты'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='addon3',
            field=models.ManyToManyField(blank=True, help_text='Возможные аддоны для первого слота аддонов', null=True,
                                         related_name='addon3', to='equipment.Addon',
                                         verbose_name='3 слот аддонов: Варианты'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='ammo_type',
            field=models.ManyToManyField(blank=True, help_text='Боеприпасы которые используются данным видом оружия',
                                         null=True, related_name='ammo_type', to='equipment.Ammo',
                                         verbose_name='Тип боепприпасов'),
        ),
    ]
