# Generated by Django 3.0.5 on 2020-12-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('equipment', '0008_auto_20201206_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='addon1',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='addon2',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='addon3',
        ),
        migrations.AddField(
            model_name='weapon',
            name='addons',
            field=models.ManyToManyField(blank=True, help_text='Возможные аддоны для первого слота аддонов',
                                         related_name='addon1', to='equipment.Addon',
                                         verbose_name='1 слот аддонов: Варианты'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='ammo_type',
            field=models.ManyToManyField(blank=True, help_text='Боеприпасы которые используются данным видом оружия',
                                         related_name='ammo_type', to='equipment.Ammo',
                                         verbose_name='Тип боепприпасов'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='one_handed',
            field=models.BooleanField(default=False,
                                      help_text='Является ли оружие одноручным. (Например, нож, пистолет)',
                                      verbose_name='Однорурчное'),
        ),
    ]
