# Generated by Django 3.0.5 on 2020-12-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('equipment', '0009_auto_20201206_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='accuracy',
            field=models.FloatField(default=0, verbose_name='Точность'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='convenience',
            field=models.FloatField(default=0, verbose_name='Удобность'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='damage',
            field=models.FloatField(default=0, verbose_name='Повреждение'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='pace_of_fire',
            field=models.FloatField(default=0, verbose_name='Скорострельность'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='ballistic',
            field=models.FloatField(default=0, verbose_name='Балистическая защита'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='burst',
            field=models.FloatField(default=0, verbose_name='Защита от разрыва'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='chemical',
            field=models.FloatField(default=0, verbose_name='Химащита'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='electrical',
            field=models.FloatField(default=0, verbose_name='Электрозащита'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='energy',
            field=models.FloatField(default=0, verbose_name='Восстановление энергии'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='explosion',
            field=models.FloatField(default=0, verbose_name='Защита от взрыва'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='healing',
            field=models.FloatField(default=0, verbose_name='Лечение'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='kick',
            field=models.FloatField(default=0, verbose_name='Гашение удара'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='psi',
            field=models.FloatField(default=0, verbose_name='Пси защита'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='radioactive',
            field=models.FloatField(default=0, verbose_name='Радиозащита'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='satiety',
            field=models.FloatField(default=0, verbose_name='Насыщение'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='thermal',
            field=models.FloatField(default=0, verbose_name='Термозащита'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Переносимый вес'),
        ),
        migrations.AlterField(
            model_name='backpack',
            name='carry_weight',
            field=models.FloatField(default=0, verbose_name='Максимальный переносимый вес'),
        ),
        migrations.AlterField(
            model_name='foodandmedicine',
            name='ballistic',
            field=models.FloatField(default=0, verbose_name='Балистическая защита'),
        ),
        migrations.AlterField(
            model_name='foodandmedicine',
            name='burst',
            field=models.FloatField(default=0, verbose_name='Защита от разрыва'),
        ),
        migrations.AlterField(
            model_name='foodandmedicine',
            name='chemical',
            field=models.FloatField(default=0, verbose_name='Химащита'),
        ),
        migrations.AlterField(
            model_name='foodandmedicine',
            name='electrical',
            field=models.FloatField(default=0, verbose_name='Электрозащита'),
        ),
        migrations.AlterField(
            model_name='foodandmedicine',
            name='energy',
            field=models.FloatField(default=0, verbose_name='Восстановление энергии'),
        ),
        migrations.AlterField(
            model_name='foodandmedicine',
            name='explosion',
            field=models.FloatField(default=0, verbose_name='Защита от взрыва'),
        ),
        migrations.AlterField(
            model_name='foodandmedicine',
            name='healing',
            field=models.FloatField(default=0, verbose_name='Лечение'),
        ),
        migrations.AlterField(
            model_name='foodandmedicine',
            name='kick',
            field=models.FloatField(default=0, verbose_name='Гашение удара'),
        ),
        migrations.AlterField(
            model_name='foodandmedicine',
            name='psi',
            field=models.FloatField(default=0, verbose_name='Пси защита'),
        ),
        migrations.AlterField(
            model_name='foodandmedicine',
            name='radioactive',
            field=models.FloatField(default=0, verbose_name='Радиозащита'),
        ),
        migrations.AlterField(
            model_name='foodandmedicine',
            name='satiety',
            field=models.FloatField(default=0, verbose_name='Насыщение'),
        ),
        migrations.AlterField(
            model_name='foodandmedicine',
            name='thermal',
            field=models.FloatField(default=0, verbose_name='Термозащита'),
        ),
        migrations.AlterField(
            model_name='foodandmedicine',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Переносимый вес'),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='ballistic',
            field=models.FloatField(default=0, verbose_name='Балистическая защита уникального шлема'),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='burst',
            field=models.FloatField(default=0, verbose_name='Защита от разрыва уникального шлема'),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='chemical',
            field=models.FloatField(default=0, verbose_name='Химащита уникального шлема'),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='electrical',
            field=models.FloatField(default=0, verbose_name='Электрозащита уникального шлема'),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='explosion',
            field=models.FloatField(default=0, verbose_name='Защита от взрыва уникального шлема'),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='kick',
            field=models.FloatField(default=0, verbose_name='Гашение удара уникального шлема'),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='psi',
            field=models.FloatField(default=0, verbose_name='Пси защита уникального шлема'),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='radioactive',
            field=models.FloatField(default=0, verbose_name='Радиоактивная уникального шлема'),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='thermal',
            field=models.FloatField(default=0, verbose_name='Термозащита уникального шлема'),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Переносимый вес уникального шлема'),
        ),
        migrations.AlterField(
            model_name='helmetupgrade',
            name='ballistic',
            field=models.FloatField(default=0, verbose_name='Балистическая защита уникального шлема'),
        ),
        migrations.AlterField(
            model_name='helmetupgrade',
            name='burst',
            field=models.FloatField(default=0, verbose_name='Защита от разрыва уникального шлема'),
        ),
        migrations.AlterField(
            model_name='helmetupgrade',
            name='chemical',
            field=models.FloatField(default=0, verbose_name='Химащита уникального шлема'),
        ),
        migrations.AlterField(
            model_name='helmetupgrade',
            name='electrical',
            field=models.FloatField(default=0, verbose_name='Электрозащита уникального шлема'),
        ),
        migrations.AlterField(
            model_name='helmetupgrade',
            name='explosion',
            field=models.FloatField(default=0, verbose_name='Защита от взрыва уникального шлема'),
        ),
        migrations.AlterField(
            model_name='helmetupgrade',
            name='kick',
            field=models.FloatField(default=0, verbose_name='Гашение удара уникального шлема'),
        ),
        migrations.AlterField(
            model_name='helmetupgrade',
            name='psi',
            field=models.FloatField(default=0, verbose_name='Пси защита уникального шлема'),
        ),
        migrations.AlterField(
            model_name='helmetupgrade',
            name='radioactive',
            field=models.FloatField(default=0, verbose_name='Радиоактивная уникального шлема'),
        ),
        migrations.AlterField(
            model_name='helmetupgrade',
            name='thermal',
            field=models.FloatField(default=0, verbose_name='Термозащита уникального шлема'),
        ),
        migrations.AlterField(
            model_name='helmetupgrade',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Переносимый вес уникального шлема'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='ballistic',
            field=models.FloatField(default=0, verbose_name='Балистическая защита уникального костюма'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='burst',
            field=models.FloatField(default=0, verbose_name='Защита от разрыва уникального костюма'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='chemical',
            field=models.FloatField(default=0, verbose_name='Химащита уникального костюма'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='electrical',
            field=models.FloatField(default=0, verbose_name='Электрозащита уникального костюма'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='explosion',
            field=models.FloatField(default=0, verbose_name='Защита от взрыва уникального костюма'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='kick',
            field=models.FloatField(default=0, verbose_name='Гашение удара уникального костюма'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='psi',
            field=models.FloatField(default=0, verbose_name='Пси защита уникального костюма'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='radioactive',
            field=models.FloatField(default=0, verbose_name='Радиоактивная уникального костюма'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='thermal',
            field=models.FloatField(default=0, verbose_name='Термозащита уникального костюма'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Переносимый вес уникального костюма'),
        ),
        migrations.AlterField(
            model_name='outfitupgrade',
            name='ballistic',
            field=models.FloatField(default=0, verbose_name='Балистическая защита уникального костюма'),
        ),
        migrations.AlterField(
            model_name='outfitupgrade',
            name='burst',
            field=models.FloatField(default=0, verbose_name='Защита от разрыва уникального костюма'),
        ),
        migrations.AlterField(
            model_name='outfitupgrade',
            name='chemical',
            field=models.FloatField(default=0, verbose_name='Химащита уникального костюма'),
        ),
        migrations.AlterField(
            model_name='outfitupgrade',
            name='electrical',
            field=models.FloatField(default=0, verbose_name='Электрозащита уникального костюма'),
        ),
        migrations.AlterField(
            model_name='outfitupgrade',
            name='explosion',
            field=models.FloatField(default=0, verbose_name='Защита от взрыва уникального костюма'),
        ),
        migrations.AlterField(
            model_name='outfitupgrade',
            name='kick',
            field=models.FloatField(default=0, verbose_name='Гашение удара уникального костюма'),
        ),
        migrations.AlterField(
            model_name='outfitupgrade',
            name='psi',
            field=models.FloatField(default=0, verbose_name='Пси защита уникального костюма'),
        ),
        migrations.AlterField(
            model_name='outfitupgrade',
            name='radioactive',
            field=models.FloatField(default=0, verbose_name='Радиоактивная уникального костюма'),
        ),
        migrations.AlterField(
            model_name='outfitupgrade',
            name='thermal',
            field=models.FloatField(default=0, verbose_name='Термозащита уникального костюма'),
        ),
        migrations.AlterField(
            model_name='outfitupgrade',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Переносимый вес уникального костюма'),
        ),
        migrations.AlterField(
            model_name='questitem',
            name='feature_num1',
            field=models.FloatField(default=0, verbose_name='Значение характеристики №1'),
        ),
        migrations.AlterField(
            model_name='questitem',
            name='feature_num2',
            field=models.FloatField(default=0, verbose_name='Значение характеристики №2'),
        ),
        migrations.AlterField(
            model_name='questitem',
            name='feature_num3',
            field=models.FloatField(default=0, verbose_name='Значение характеристики №3'),
        ),
        migrations.AlterField(
            model_name='questitem',
            name='feature_num4',
            field=models.FloatField(default=0, verbose_name='Значение характеристики №4'),
        ),
        migrations.AlterField(
            model_name='questitem',
            name='feature_num5',
            field=models.FloatField(default=0, verbose_name='Значение характеристики №5'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='accuracy',
            field=models.FloatField(default=0, verbose_name='Точность оружия'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='convenience',
            field=models.FloatField(default=0, verbose_name='Удобность оружия'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='damage',
            field=models.FloatField(default=0, verbose_name='Повреждение оружия'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='pace_of_fire',
            field=models.FloatField(default=0, verbose_name='Скорострельность оружия'),
        ),
        migrations.AlterField(
            model_name='weaponupgrade',
            name='accuracy',
            field=models.FloatField(default=0, verbose_name='Точность оружия'),
        ),
        migrations.AlterField(
            model_name='weaponupgrade',
            name='convenience',
            field=models.FloatField(default=0, verbose_name='Удобность оружия'),
        ),
        migrations.AlterField(
            model_name='weaponupgrade',
            name='damage',
            field=models.FloatField(default=0, verbose_name='Повреждение оружия'),
        ),
        migrations.AlterField(
            model_name='weaponupgrade',
            name='pace_of_fire',
            field=models.FloatField(default=0, verbose_name='Скорострельность оружия'),
        ),
    ]
