# Generated by Django 3.0.5 on 2021-01-03 19:13

import equipment.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('equipment', '0010_auto_20201206_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ammo',
            options={'verbose_name': 'Тип боеприпасов', 'verbose_name_plural': 'Боеприпасы'},
        ),
        migrations.AlterField(
            model_name='equipitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя предмета'),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.ImageField(upload_to=equipment.models.upload_to, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='equipped_icon',
            field=models.ImageField(default='postap.png', upload_to='equip/outfit/full',
                                    verbose_name='Иконка персонажа в костюме'),
        ),
    ]
