# Generated by Django 3.0.5 on 2021-01-07 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('equipment', '0012_auto_20210107_1055'),
        ('users', '0005_auto_20210107_1055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equip',
        ),
    ]
