# Generated by Django 3.0.5 on 2021-01-07 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('equipment', '0013_delete_equip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addonoutfit',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='addonoutfit',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='addonoutfit',
            name='convenience',
        ),
        migrations.RemoveField(
            model_name='addonoutfit',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='addonoutfit',
            name='pace_of_fire',
        ),
    ]
