# Generated by Django 3.0.5 on 2021-02-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('equipment', '0015_device_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipitem',
            name='mass',
            field=models.FloatField(default=0.0),
        ),
    ]
