# Generated by Django 3.0.5 on 2021-02-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('equipment', '0016_equipitem_mass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addonoutfit',
            old_name='arts_max',
            new_name='containers',
        ),
        migrations.RenameField(
            model_name='outfit',
            old_name='arts_max',
            new_name='containers',
        ),
        migrations.RenameField(
            model_name='outfitupgrade',
            old_name='arts_max',
            new_name='containers',
        ),
        migrations.RemoveField(
            model_name='addonoutfit',
            name='modules_max',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='modules_max',
        ),
        migrations.RemoveField(
            model_name='outfitupgrade',
            name='modules_max',
        ),
        migrations.AlterField(
            model_name='addonoutfit',
            name='ballistic',
            field=models.FloatField(default=0, verbose_name='Балистическая защита'),
        ),
        migrations.AlterField(
            model_name='addonoutfit',
            name='burst',
            field=models.FloatField(default=0, verbose_name='Защита от разрыва'),
        ),
        migrations.AlterField(
            model_name='addonoutfit',
            name='chemical',
            field=models.FloatField(default=0, verbose_name='Химащита'),
        ),
        migrations.AlterField(
            model_name='addonoutfit',
            name='electrical',
            field=models.FloatField(default=0, verbose_name='Электрозащита'),
        ),
        migrations.AlterField(
            model_name='addonoutfit',
            name='explosion',
            field=models.FloatField(default=0, verbose_name='Защита от взрыва'),
        ),
        migrations.AlterField(
            model_name='addonoutfit',
            name='kick',
            field=models.FloatField(default=0, verbose_name='Гашение удара'),
        ),
        migrations.AlterField(
            model_name='addonoutfit',
            name='psi',
            field=models.FloatField(default=0, verbose_name='Пси защита'),
        ),
        migrations.AlterField(
            model_name='addonoutfit',
            name='radioactive',
            field=models.FloatField(default=0, verbose_name='Радиоактивная'),
        ),
        migrations.AlterField(
            model_name='addonoutfit',
            name='thermal',
            field=models.FloatField(default=0, verbose_name='Термозащита'),
        ),
        migrations.AlterField(
            model_name='addonoutfit',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Переносимый вес'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='ballistic',
            field=models.FloatField(default=0, verbose_name='Балистическая защита'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='burst',
            field=models.FloatField(default=0, verbose_name='Защита от разрыва'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='chemical',
            field=models.FloatField(default=0, verbose_name='Химащита'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='electrical',
            field=models.FloatField(default=0, verbose_name='Электрозащита'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='explosion',
            field=models.FloatField(default=0, verbose_name='Защита от взрыва'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='kick',
            field=models.FloatField(default=0, verbose_name='Гашение удара'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='psi',
            field=models.FloatField(default=0, verbose_name='Пси защита'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='radioactive',
            field=models.FloatField(default=0, verbose_name='Радиоактивная'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='thermal',
            field=models.FloatField(default=0, verbose_name='Термозащита'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Переносимый вес'),
        ),
        migrations.AlterField(
            model_name='outfitupgrade',
            name='ballistic',
            field=models.FloatField(default=0, verbose_name='Балистическая защита'),
        ),
        migrations.AlterField(
            model_name='outfitupgrade',
            name='burst',
            field=models.FloatField(default=0, verbose_name='Защита от разрыва'),
        ),
        migrations.AlterField(
            model_name='outfitupgrade',
            name='chemical',
            field=models.FloatField(default=0, verbose_name='Химащита'),
        ),
        migrations.AlterField(
            model_name='outfitupgrade',
            name='electrical',
            field=models.FloatField(default=0, verbose_name='Электрозащита'),
        ),
        migrations.AlterField(
            model_name='outfitupgrade',
            name='explosion',
            field=models.FloatField(default=0, verbose_name='Защита от взрыва'),
        ),
        migrations.AlterField(
            model_name='outfitupgrade',
            name='kick',
            field=models.FloatField(default=0, verbose_name='Гашение удара'),
        ),
        migrations.AlterField(
            model_name='outfitupgrade',
            name='psi',
            field=models.FloatField(default=0, verbose_name='Пси защита'),
        ),
        migrations.AlterField(
            model_name='outfitupgrade',
            name='radioactive',
            field=models.FloatField(default=0, verbose_name='Радиоактивная'),
        ),
        migrations.AlterField(
            model_name='outfitupgrade',
            name='thermal',
            field=models.FloatField(default=0, verbose_name='Термозащита'),
        ),
        migrations.AlterField(
            model_name='outfitupgrade',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Переносимый вес'),
        ),
    ]
