# Generated by Django 3.0.5 on 2021-02-25 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0018_auto_20210212_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipitem',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='equip_items', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Профиль пользователя'),
        ),
    ]
