# Generated by Django 3.0.5 on 2021-02-16 20:59

import ckeditor.fields
import django.db.models.deletion
import roleplay.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('users', '0008_auto_20210216_2221'),
        ('equipment', '0018_auto_20210212_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to=roleplay.models.upload_to, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Территория',
                'verbose_name_plural': 'Территории',
            },
        ),
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to=roleplay.models.upload_to, verbose_name='Иконка')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                           to='roleplay.Area', verbose_name='Локация')),
                ('transitions', models.ManyToManyField(blank=True, related_name='_sublocation_transitions_+',
                                                       to='roleplay.SubLocation', verbose_name='Переходы')),
            ],
            options={
                'verbose_name': 'Подлокация',
                'verbose_name_plural': 'Подлокации',
            },
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('full_name', models.CharField(max_length=150, verbose_name='Полное Имя')),
                ('bio', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('rank', models.PositiveSmallIntegerField(default=1, verbose_name='Ранг')),
                ('avatar', models.ImageField(upload_to=roleplay.models.npc_upload_to_ava, verbose_name='Аватар')),
                ('image', models.ImageField(help_text='(Желательно в полный рост и по центру)',
                                            upload_to=roleplay.models.npc_upload_to_img,
                                            verbose_name='Изображение персонажа')),
                ('money', models.IntegerField(default=0, verbose_name='Деньги')),
                ('inf', models.BooleanField(default=True, verbose_name='Бесконечны ли деньги')),
                ('coef', models.FloatField(verbose_name='Коєфициент цены')),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                              related_name='rp_npc_trader', to='users.Faction',
                                              verbose_name='Группировка')),
                ('items', models.ManyToManyField(blank=True, to='equipment.Item', verbose_name='Предметы на продажу')),
                ('sublocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                                  to='roleplay.SubLocation', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Торговец',
                'verbose_name_plural': 'Торговцы',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to=roleplay.models.upload_to, verbose_name='Иконка')),
                ('transitions',
                 models.ManyToManyField(blank=True, related_name='_location_transitions_+', to='roleplay.Location',
                                        verbose_name='Переходы')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='roleplay.Location', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='area',
            name='transitions',
            field=models.ManyToManyField(blank=True, related_name='_area_transitions_+', to='roleplay.Area',
                                         verbose_name='Переходы'),
        ),
    ]
