# Generated by Django 3.0.5 on 2021-02-16 21:32

import django.core.validators
import roleplay.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('roleplay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='coef',
        ),
        migrations.AddField(
            model_name='trader',
            name='coef_buy',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.2),
                                                           django.core.validators.MaxValueValidator(5)],
                                    verbose_name='Коєфициент покупки'),
        ),
        migrations.AddField(
            model_name='trader',
            name='coef_trade',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.2),
                                                           django.core.validators.MaxValueValidator(5)],
                                    verbose_name='Коєфициент продажи'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='avatar',
            field=models.ImageField(default='img/profile/no_data.gif', upload_to=roleplay.models.npc_upload_to_ava,
                                    verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='rank',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1),
                                                                          django.core.validators.MaxValueValidator(10)],
                                                   verbose_name='Ранг'),
        ),
    ]
