# Generated by Django 3.0.5 on 2021-03-06 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('roleplay', '0004_auto_20210305_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='areas', to='roleplay.Location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='area',
            name='x_coord',
            field=models.FloatField(default=0, help_text='Расположение элемента по X координате',
                                    verbose_name='X координата'),
        ),
        migrations.AlterField(
            model_name='area',
            name='y_coord',
            field=models.FloatField(default=0, help_text='Расположение элемента по Y координате',
                                    verbose_name='Y координата'),
        ),
        migrations.AlterField(
            model_name='sublocation',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='sublocations', to='roleplay.Area', verbose_name='Локация'),
        ),
    ]
