# Generated by Django 3.0.5 on 2021-03-06 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('roleplay', '0005_auto_20210306_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='sublocation',
        ),
        migrations.RemoveField(
            model_name='npcminigame',
            name='sublocation',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='sublocation',
        ),
        migrations.AddField(
            model_name='mechanic',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='npc_mechanic', to='roleplay.Area', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='npcminigame',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='npc_minigame', to='roleplay.Area', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='trader',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='npc_trader', to='roleplay.Area', verbose_name='Локация'),
        ),
    ]
