# Generated by Django 3.0.5 on 2021-03-09 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('roleplay', '0006_auto_20210306_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mechanic',
            options={},
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='area',
        ),
        migrations.RemoveField(
            model_name='npcminigame',
            name='area',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='area',
        ),
        migrations.AddField(
            model_name='mechanic',
            name='sublocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='npc_mechanics', to='roleplay.SubLocation', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='npcminigame',
            name='sublocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='npc_minigames', to='roleplay.SubLocation', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='trader',
            name='sublocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='npc_traders', to='roleplay.SubLocation', verbose_name='Локация'),
        ),
    ]
