# Generated by Django 3.0.13 on 2021-04-06 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0003_auto_20210401_0103'),
        ('roleplay', '0008_sublocation_type_of_subloc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampFire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название чата')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roleplay.Area',
                                           verbose_name='Територия')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.Chat',
                                           verbose_name='Чат')),
            ],
        ),
    ]
