# Generated by Django 3.0.13 on 2021-04-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('roleplay', '0009_campfire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campfire',
            options={'verbose_name': 'Костер (ролевой чат)', 'verbose_name_plural': 'Костры (ролевые чаты)'},
        ),
        migrations.AddField(
            model_name='campfire',
            name='bg',
            field=models.ImageField(null=True, upload_to='roleplay/campfire/bg/', verbose_name='Фон'),
        ),
        migrations.AddField(
            model_name='campfire',
            name='image',
            field=models.ImageField(null=True, upload_to='roleplay/campfire/preview/', verbose_name='Превью'),
        ),
    ]
