# Generated by Django 3.0.13 on 2021-03-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0002_chat_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='preview',
            field=models.ImageField(default='roleplay/default/campfire.jpg', upload_to='roleplay/campfire',
                                    verbose_name='Превью'),
        ),
        migrations.AddField(
            model_name='chat',
            name='roleplay',
            field=models.BooleanField(default=False, verbose_name='Чат ролевой игры'),
        ),
    ]
