# Generated by Django 3.0.5 on 2020-05-16 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('voting', '0002_auto_20200516_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modvoting',
            options={'verbose_name': 'Выбор лучших модификаций', 'verbose_name_plural': 'Выборы лучших модификаций'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
