# Generated by Django 3.0.5 on 2020-05-16 17:11

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('voting', '0003_auto_20200516_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_title', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('image', stdimage.models.StdImageField(blank=True, default='postap.png', upload_to='entries',
                                                        verbose_name='Изображение')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Poll')),
            ],
            options={
                'verbose_name': 'Вариант голосования',
                'verbose_name_plural': 'Варианты голосования',
            },
        ),
    ]
