# Generated by Django 3.0.5 on 2020-05-17 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('voting', '0004_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollcategories',
            options={'verbose_name': 'Категория опросов', 'verbose_name_plural': 'Категории опросов'},
        ),
    ]
