# Generated by Django 3.0.5 on 2020-07-29 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('voting', '0005_auto_20200518_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modchoice',
            name='mod',
        ),
        migrations.RemoveField(
            model_name='modchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='modvoting',
            name='category',
        ),
        migrations.RemoveField(
            model_name='modvotingcategories',
            name='pollcategories_ptr',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='category',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='question',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='category',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='ModChoice',
        ),
        migrations.DeleteModel(
            name='ModVoting',
        ),
        migrations.DeleteModel(
            name='ModVotingCategories',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='PollCategories',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.DeleteModel(
            name='Voting',
        ),
        migrations.DeleteModel(
            name='VotingCategories',
        ),
    ]
