# Generated by Django 3.0.5 on 2020-04-22 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='entry',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='entries.EntryNews'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image1',
            field=models.ImageField(blank=True, upload_to='entries/gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image10',
            field=models.ImageField(blank=True, upload_to='entries/gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image11',
            field=models.ImageField(blank=True, upload_to='entries/gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image12',
            field=models.ImageField(blank=True, upload_to='entries/gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image13',
            field=models.ImageField(blank=True, upload_to='entries/gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image14',
            field=models.ImageField(blank=True, upload_to='entries/gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image15',
            field=models.ImageField(blank=True, upload_to='entries/gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image2',
            field=models.ImageField(blank=True, upload_to='entries/gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image3',
            field=models.ImageField(blank=True, upload_to='entries/gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image4',
            field=models.ImageField(blank=True, upload_to='entries/gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image5',
            field=models.ImageField(blank=True, upload_to='entries/gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image6',
            field=models.ImageField(blank=True, upload_to='entries/gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image7',
            field=models.ImageField(blank=True, upload_to='entries/gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image8',
            field=models.ImageField(blank=True, upload_to='entries/gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image9',
            field=models.ImageField(blank=True, upload_to='entries/gallery'),
        ),
    ]
