# Generated by Django 3.0.5 on 2020-05-01 21:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entryarticle',
            old_name='gallery',
            new_name='objgallery',
        ),
        migrations.RenameField(
            model_name='entrynews',
            old_name='gallery',
            new_name='objgallery',
        ),
    ]
