# Generated by Django 3.0.5 on 2020-05-03 12:10

import entries.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0002_auto_20200502_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=stdimage.models.StdImageField(blank=True, default='postap.png', upload_to='entries',
                                                verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='entryarticle',
            name='image',
            field=stdimage.models.StdImageField(default='postap.png', null=True,
                                                upload_to=entries.models.upload_to_entries, verbose_name='Илюстрация'),
        ),
        migrations.AlterField(
            model_name='entrynews',
            name='image',
            field=stdimage.models.StdImageField(default='postap.png', null=True,
                                                upload_to=entries.models.upload_to_entries, verbose_name='Илюстрация'),
        ),
    ]
