# Generated by Django 3.0.5 on 2020-04-22 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0002_auto_20200423_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrynews',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='entries.Gallery'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='entry',
            field=models.CharField(blank=True, max_length=100, verbose_name='Вид записи'),
        ),
    ]
