# Generated by Django 3.0.5 on 2020-08-08 13:33

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('gallery', '0021_auto_20200729_2328'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0002_auto_20200808_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL,
                                    verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='news',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='entries.NewsCategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='news',
            name='objgallery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='gallery.Gallery'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.',
                                                  through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='mod',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='entries.Author', verbose_name='Автор модификации'),
        ),
        migrations.AddField(
            model_name='mod',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entries.ModCategory',
                                    verbose_name='Категория модов'),
        ),
        migrations.AddField(
            model_name='mod',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entries.File',
                                    verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='mod',
            name='gameobj',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='entries.Game',
                                    verbose_name='Модифицируемая игра'),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL,
                                    verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='entries.ImageGalleryCategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='objgallery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='gallery.Gallery'),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.',
                                                  through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='guide',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='modguides',
                                    to='entries.Mod', verbose_name='Модификация'),
        ),
        migrations.AddField(
            model_name='file',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL,
                                    verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='file',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='entries.FileCategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='file',
            name='objgallery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='gallery.Gallery'),
        ),
        migrations.AddField(
            model_name='file',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.',
                                                  through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='faq',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL,
                                    verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entries.FaqCategory',
                                    verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='faq',
            name='objgallery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='gallery.Gallery'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL,
                                    verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='entries.ArticleCategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='article',
            name='objgallery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='gallery.Gallery'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.',
                                                  through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
