# Generated by Django 3.0.5 on 2020-04-23 20:30

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0003_auto_20200423_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='descript',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='descript',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='entrynews',
            name='shortDescript',
            field=tinymce.models.HTMLField(verbose_name='Короткое описание'),
        ),
    ]
