# Generated by Django 3.0.5 on 2020-04-23 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0006_entry_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='entry',
        ),
    ]
