# Generated by Django 3.0.5 on 2020-05-04 17:07

import django.core.validators
import django.db.models.deletion
import entries.models
import stdimage.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0006_auto_20200504_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('slug', models.SlugField(help_text='Навзание, которое будет отображаться в URL', unique=True)),
                ('nickname', models.CharField(max_length=200, verbose_name='Никнейм автора')),
                ('bio', tinymce.models.HTMLField()),
                ('domain', models.CharField(
                    choices=[('youtuber', 'Видео блогер'), ('bloger', 'Блогер'), ('moder', 'Мододел'),
                             ('musician', 'Музыкант'), ('painter', 'Художник'), ('artist', 'Творец'),
                             ('writer', 'Писатель'), ('unique_person', 'Уникальная персона')], max_length=200,
                    verbose_name='Сфера деятельности')),
                ('avatar', stdimage.models.StdImageField(upload_to=entries.models.upload_to_authors,
                                                         verbose_name='Аватар автора')),
                ('bg', stdimage.models.StdImageField(upload_to=entries.models.upload_to_authors,
                                                     verbose_name='Аватар автора')),
                ('vk', models.URLField(blank=True)),
                ('discord', models.URLField(blank=True)),
                ('tg', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('twitch', models.URLField(blank=True)),
                ('artstation', models.URLField(blank=True)),
                ('devianart', models.URLField(blank=True)),
                ('site', models.URLField(blank=True)),
                ('other1', models.URLField(blank=True)),
                ('other2', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='CategoriesMods',
            fields=[
                ('categories_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='entries.Categories')),
            ],
            options={
                'verbose_name': 'Категория модов',
                'verbose_name_plural': 'Категории модов',
            },
            bases=('entries.categories',),
        ),
        migrations.AlterField(
            model_name='games',
            name='logo',
            field=models.FileField(blank=True, help_text='Форматы svg, png, gif',
                                   upload_to=entries.models.upload_to_games,
                                   validators=[django.core.validators.FileExtensionValidator(['png', 'gif', 'svg'])],
                                   verbose_name='Логотип игры'),
        ),
        migrations.CreateModel(
            name='EntryMod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plot', tinymce.models.HTMLField(blank=True, verbose_name='Коротко о сюжете')),
                ('features', tinymce.models.HTMLField(blank=True, verbose_name='Особенности')),
                ('innovations', tinymce.models.HTMLField(blank=True, verbose_name='Нововведения')),
                ('gameplay', tinymce.models.HTMLField(blank=True, verbose_name='Гемйплей')),
                ('locations', tinymce.models.HTMLField(blank=True, verbose_name='Локации')),
                ('weapons', tinymce.models.HTMLField(blank=True, verbose_name='Другое')),
                ('other',
                 tinymce.models.HTMLField(blank=True, verbose_name='Другие особенности и нововведения модификации')),
                ('author',
                 models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                   to='entries.Author', verbose_name='Автор модификации')),
                ('categories',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entries.CategoriesMods',
                                   verbose_name='Категория модов')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entries.EntryFile',
                                           verbose_name='Файл')),
            ],
        ),
    ]
