# Generated by Django 3.0.5 on 2020-05-04 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gallery', '0014_auto_20200503_1455'),
        ('entries', '0007_auto_20200504_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrymod',
            name='gameobj',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='entries.Games',
                                    verbose_name='Модифицируемая игра'),
        ),
        migrations.AddField(
            model_name='entrymod',
            name='slug',
            field=models.SlugField(default=None, help_text='Навзание, которое будет отображаться в URL', unique=True),
        ),
        migrations.AddField(
            model_name='entrymod',
            name='title',
            field=models.CharField(default=None, max_length=250, verbose_name='Название игры'),
        ),
        migrations.AlterField(
            model_name='entryarticle',
            name='objgallery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='gallery.Gallery'),
        ),
        migrations.AlterField(
            model_name='entryfile',
            name='objgallery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='gallery.Gallery'),
        ),
        migrations.AlterField(
            model_name='entrynews',
            name='objgallery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='gallery.Gallery'),
        ),
    ]
