# Generated by Django 3.0.5 on 2020-05-04 22:07

import django.db.models.deletion
import entries.models
import stdimage.models
import taggit.managers
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('gallery', '0014_auto_20200503_1455'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0008_auto_20200504_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesImages',
            fields=[
                ('categories_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='entries.Categories')),
            ],
            options={
                'verbose_name': 'Категория галереи',
                'verbose_name_plural': 'Категории галереи',
            },
            bases=('entries.categories',),
        ),
        migrations.AlterModelOptions(
            name='entrymod',
            options={'verbose_name': 'Мод', 'verbose_name_plural': 'Моды'},
        ),
        migrations.AlterField(
            model_name='entrymod',
            name='title',
            field=models.CharField(default=None, max_length=250, verbose_name='Название мода'),
        ),
        migrations.CreateModel(
            name='EntryImageGallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug',
                 models.SlugField(help_text='Навзание, которое будет отображаться в URL', max_length=25, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('shortDescript', tinymce.models.HTMLField(verbose_name='Короткое описание')),
                ('descript', tinymce.models.HTMLField(verbose_name='Описание')),
                ('image', stdimage.models.StdImageField(default='postap.png', null=True,
                                                        upload_to=entries.models.upload_to_entries,
                                                        verbose_name='Илюстрация')),
                ('inTop', models.BooleanField(blank='True', default=False, verbose_name='Закрепить материал')),
                ('atMain',
                 models.BooleanField(blank='True', default=False, verbose_name='Вывести материал на главную страницу')),
                ('author',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL,
                                   verbose_name='Автор')),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                                 to='entries.CategoriesImages', verbose_name='Категория')),
                ('objgallery',
                 models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   to='gallery.Gallery')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.',
                                                         through='taggit.TaggedItem', to='taggit.Tag',
                                                         verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
