# Generated by Django 3.0.5 on 2020-05-10 17:38

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0009_auto_20200505_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Навзание квеста')),
                ('type0f', models.CharField(
                    choices=[('main', 'Сюжетный квест'), ('side', 'Побочный квест'), ('additional', 'Дополнительный'),
                             ('items', 'Метонахождение квестовых предметов'), ('tools', 'Метонахождение инстурментов'),
                             ('interesting', 'Интересности'), ('easter_eggs', 'Пасхалки'), ('other', 'Другое')],
                    max_length=100, verbose_name='Тип гайда')),
                ('descript', tinymce.models.HTMLField(verbose_name='Описание квеста')),
                ('solution', tinymce.models.HTMLField(verbose_name='Решение квеста')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entries.EntryMod',
                                          verbose_name='Модификация')),
            ],
            options={
                'verbose_name': 'Гайд по прохождению',
                'verbose_name_plural': 'Гайды по прохождению',
            },
        ),
    ]
