# Generated by Django 3.0.5 on 2020-04-24 17:39

import entries.models
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('entries', '0009_auto_20200424_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(default='postap.png', null=True, upload_to=entries.models.upload_to_entries,
                                    verbose_name='Илюстрация'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.',
                                                  through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image1',
            field=models.ImageField(blank=True, upload_to=entries.models.upload_to),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image10',
            field=models.ImageField(blank=True, upload_to=entries.models.upload_to),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image11',
            field=models.ImageField(blank=True, upload_to=entries.models.upload_to),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image12',
            field=models.ImageField(blank=True, upload_to=entries.models.upload_to),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image13',
            field=models.ImageField(blank=True, upload_to=entries.models.upload_to),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image14',
            field=models.ImageField(blank=True, upload_to=entries.models.upload_to),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image15',
            field=models.ImageField(blank=True, upload_to=entries.models.upload_to),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image2',
            field=models.ImageField(blank=True, upload_to=entries.models.upload_to),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image3',
            field=models.ImageField(blank=True, upload_to=entries.models.upload_to),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image4',
            field=models.ImageField(blank=True, upload_to=entries.models.upload_to),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image5',
            field=models.ImageField(blank=True, upload_to=entries.models.upload_to),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image6',
            field=models.ImageField(blank=True, upload_to=entries.models.upload_to),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image7',
            field=models.ImageField(blank=True, upload_to=entries.models.upload_to),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image8',
            field=models.ImageField(blank=True, upload_to=entries.models.upload_to),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image9',
            field=models.ImageField(blank=True, upload_to=entries.models.upload_to),
        ),
    ]
