# Generated by Django 3.0.5 on 2020-05-10 20:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0010_entryguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrynews',
            name='descript',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='entrynews',
            name='shortDescript',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Короткое описание'),
        ),
    ]
