# Generated by Django 3.0.5 on 2020-04-25 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0010_auto_20200424_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryArticle',
            fields=[
                ('entrynews_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='entries.EntryNews')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
            bases=('entries.entrynews',),
        ),
        migrations.RenameModel(
            old_name='CategoriesArticles',
            new_name='CategoriesArticle',
        ),
        migrations.AlterModelOptions(
            name='categoriesarticle',
            options={'verbose_name': 'Категория статей', 'verbose_name_plural': 'Категории статей'},
        ),
    ]
