# Generated by Django 3.0.5 on 2020-04-25 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0011_auto_20200425_1611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntryArticle',
        ),
    ]
