# Generated by Django 3.0.5 on 2020-04-25 13:46

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0012_delete_entryarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryArticle',
            fields=[
                ('entry_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='entries.Entry')),
                ('shortDescript', tinymce.models.HTMLField(null=True, verbose_name='Короткое описание')),
                ('source', models.URLField(blank=True, null=True, verbose_name='Источник')),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                                 to='entries.CategoriesArticle', verbose_name='Категория')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='entries.Gallery')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
            bases=('entries.entry',),
        ),
    ]
