# Generated by Django 3.0.5 on 2020-05-14 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0012_auto_20200511_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesarticle',
            name='categories_ptr',
        ),
        migrations.RemoveField(
            model_name='categoriesfiles',
            name='categories_ptr',
        ),
        migrations.RemoveField(
            model_name='categoriesimages',
            name='categories_ptr',
        ),
        migrations.RemoveField(
            model_name='categoriesmods',
            name='categories_ptr',
        ),
        migrations.RemoveField(
            model_name='categoriesnews',
            name='categories_ptr',
        ),
        migrations.AlterField(
            model_name='entryarticle',
            name='categories',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='entryfile',
            name='categories',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='entryguide',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='modguides',
                                    to='entries.EntryMod', verbose_name='Модификация'),
        ),
        migrations.AlterField(
            model_name='entryimagegallery',
            name='categories',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='entrymod',
            name='categories',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='entrynews',
            name='categories',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='CategoriesArticle',
        ),
        migrations.DeleteModel(
            name='CategoriesFiles',
        ),
        migrations.DeleteModel(
            name='CategoriesImages',
        ),
        migrations.DeleteModel(
            name='CategoriesMods',
        ),
        migrations.DeleteModel(
            name='CategoriesNews',
        ),
    ]
