# Generated by Django 3.0.5 on 2020-04-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0013_entryarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='objID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gallery',
            name='objID',
            field=models.IntegerField(default=0),
        ),
    ]
