# Generated by Django 3.0.5 on 2020-05-14 21:29

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0013_auto_20200515_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
                ('slug',
                 models.CharField(help_text='Навзание, которое будет отображаться в URL', max_length=25, unique=True)),
                ('descript', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('image', stdimage.models.StdImageField(blank=True, default='postap.png', upload_to='entries',
                                                        verbose_name='Изображение')),
                ('icon', models.FileField(blank=True, help_text='Форматы svg, png, gif', upload_to='entries/categories',
                                          validators=[
                                              django.core.validators.FileExtensionValidator(['png', 'gif', 'svg'])],
                                          verbose_name='Иконка категории')),
            ],
            options={
                'verbose_name': 'Категория статей',
                'verbose_name_plural': 'Категории статей',
            },
        ),
        migrations.CreateModel(
            name='CategoriesFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
                ('slug',
                 models.CharField(help_text='Навзание, которое будет отображаться в URL', max_length=25, unique=True)),
                ('descript', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('image', stdimage.models.StdImageField(blank=True, default='postap.png', upload_to='entries',
                                                        verbose_name='Изображение')),
                ('icon', models.FileField(blank=True, help_text='Форматы svg, png, gif', upload_to='entries/categories',
                                          validators=[
                                              django.core.validators.FileExtensionValidator(['png', 'gif', 'svg'])],
                                          verbose_name='Иконка категории')),
            ],
            options={
                'verbose_name': 'Категория файлов',
                'verbose_name_plural': 'Категории файлов',
            },
        ),
        migrations.CreateModel(
            name='CategoriesImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
                ('slug',
                 models.CharField(help_text='Навзание, которое будет отображаться в URL', max_length=25, unique=True)),
                ('descript', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('image', stdimage.models.StdImageField(blank=True, default='postap.png', upload_to='entries',
                                                        verbose_name='Изображение')),
                ('icon', models.FileField(blank=True, help_text='Форматы svg, png, gif', upload_to='entries/categories',
                                          validators=[
                                              django.core.validators.FileExtensionValidator(['png', 'gif', 'svg'])],
                                          verbose_name='Иконка категории')),
            ],
            options={
                'verbose_name': 'Категория галереи',
                'verbose_name_plural': 'Категории галереи',
            },
        ),
        migrations.CreateModel(
            name='CategoriesMods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
                ('slug',
                 models.CharField(help_text='Навзание, которое будет отображаться в URL', max_length=25, unique=True)),
                ('descript', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('image', stdimage.models.StdImageField(blank=True, default='postap.png', upload_to='entries',
                                                        verbose_name='Изображение')),
                ('icon', models.FileField(blank=True, help_text='Форматы svg, png, gif', upload_to='entries/categories',
                                          validators=[
                                              django.core.validators.FileExtensionValidator(['png', 'gif', 'svg'])],
                                          verbose_name='Иконка категории')),
            ],
            options={
                'verbose_name': 'Категория модов',
                'verbose_name_plural': 'Категории модов',
            },
        ),
        migrations.CreateModel(
            name='CategoriesNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
                ('slug',
                 models.CharField(help_text='Навзание, которое будет отображаться в URL', max_length=25, unique=True)),
                ('descript', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('image', stdimage.models.StdImageField(blank=True, default='postap.png', upload_to='entries',
                                                        verbose_name='Изображение')),
                ('icon', models.FileField(blank=True, help_text='Форматы svg, png, gif', upload_to='entries/categories',
                                          validators=[
                                              django.core.validators.FileExtensionValidator(['png', 'gif', 'svg'])],
                                          verbose_name='Иконка категории')),
            ],
        ),
        migrations.AlterField(
            model_name='entryarticle',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='entries.CategoriesArticle', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='entryfile',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='entries.CategoriesFiles', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='entryimagegallery',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='entries.CategoriesImages', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='entrymod',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entries.CategoriesMods',
                                    verbose_name='Категория модов'),
        ),
        migrations.AlterField(
            model_name='entrynews',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='entries.CategoriesNews', verbose_name='Категория'),
        ),
    ]
