# Generated by Django 3.0.5 on 2020-05-14 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0014_auto_20200515_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriesnews',
            options={'verbose_name': 'Категория новостей', 'verbose_name_plural': 'Категории новостей'},
        ),
    ]
