# Generated by Django 3.0.5 on 2020-04-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0015_auto_20200425_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
