# Generated by Django 3.0.5 on 2020-05-14 21:36

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
import stdimage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0017_auto_20200515_0034'),
        ('entries', '0015_auto_20200515_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesFaq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=150, verbose_name='Название категории')),
                ('slug',
                 models.CharField(default='', help_text='Навзание, которое будет отображаться в URL', max_length=25,
                                  unique=True)),
                ('descript', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Описание')),
                ('image',
                 stdimage.models.StdImageField(blank=True, default='postap.png', null=True, upload_to='entries',
                                               verbose_name='Изображение')),
                ('icon', models.FileField(blank=True, help_text='Форматы svg, png, gif', null=True,
                                          upload_to='entries/categories', validators=[
                        django.core.validators.FileExtensionValidator(['png', 'gif', 'svg'])],
                                          verbose_name='Иконка категории')),
            ],
            options={
                'verbose_name': 'Категория FAQ',
                'verbose_name_plural': 'Категории FAQ',
            },
        ),
        migrations.CreateModel(
            name='EntryFaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400, verbose_name='Вопрос')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('questionDescript', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание вопроса')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание ответа')),
                ('posted', models.BooleanField(default=True, verbose_name='Материал опубликован')),
                ('author',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL,
                                   verbose_name='Автор')),
                ('category',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entries.CategoriesFaq',
                                   verbose_name='Категория')),
                ('objgallery',
                 models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   to='gallery.Gallery')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Часто задаваемые вопросы',
            },
        ),
    ]
