# Generated by Django 3.0.5 on 2020-05-14 22:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0016_categoriesfaq_entryfaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryfaq',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание ответа'),
        ),
        migrations.AlterField(
            model_name='entryfaq',
            name='questionDescript',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание вопроса'),
        ),
    ]
