# Generated by Django 3.0.5 on 2020-05-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0017_auto_20200515_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrymod',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='entrymod',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='entrymod',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
