# Generated by Django 3.0.5 on 2020-04-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0017_auto_20200425_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
