# Generated by Django 3.0.5 on 2020-04-25 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0018_auto_20200425_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryarticle',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='entryarticle',
            name='entry_ptr',
        ),
        migrations.RemoveField(
            model_name='entryarticle',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='entrynews',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='entrynews',
            name='entry_ptr',
        ),
        migrations.RemoveField(
            model_name='entrynews',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='EntryArticle',
        ),
        migrations.DeleteModel(
            name='EntryNews',
        ),
    ]
