# Generated by Django 3.0.5 on 2020-05-15 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0018_auto_20200515_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrymod',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='entrymod',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='entrymod',
            name='vote_score',
        ),
    ]
