# Generated by Django 3.0.5 on 2020-04-25 19:36

import django.db.models.deletion
import entries.models
import taggit.managers
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0019_auto_20200425_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug',
                 models.SlugField(help_text='Навзание, которое будет отображаться в URL', max_length=25, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('descript', tinymce.models.HTMLField(verbose_name='Описание')),
                ('shortDescript', tinymce.models.HTMLField(verbose_name='Короткое описание')),
                ('source', models.URLField(blank=True, verbose_name='Источник')),
                ('image', models.ImageField(default='postap.png', null=True, upload_to=entries.models.upload_to_entries,
                                            verbose_name='Илюстрация')),
                ('inTop', models.BooleanField(blank='True', default=False, verbose_name='Закрепить материал')),
                ('atMain',
                 models.BooleanField(blank='True', default=False, verbose_name='Вывести материал на главную страницу')),
                ('author',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL,
                                   verbose_name='Автор')),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                                 to='entries.CategoriesNews', verbose_name='Категория')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='entries.Gallery')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.',
                                                         through='taggit.TaggedItem', to='taggit.Tag',
                                                         verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='EntryArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug',
                 models.SlugField(help_text='Навзание, которое будет отображаться в URL', max_length=25, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('descript', tinymce.models.HTMLField(verbose_name='Описание')),
                ('shortDescript', tinymce.models.HTMLField(verbose_name='Короткое описание')),
                ('source', models.URLField(blank=True, verbose_name='Источник')),
                ('image', models.ImageField(default='postap.png', null=True, upload_to=entries.models.upload_to_entries,
                                            verbose_name='Илюстрация')),
                ('inTop', models.BooleanField(blank='True', default=False, verbose_name='Закрепить материал')),
                ('atMain',
                 models.BooleanField(blank='True', default=False, verbose_name='Вывести материал на главную страницу')),
                ('author',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL,
                                   verbose_name='Автор')),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                                 to='entries.CategoriesArticle', verbose_name='Категория')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='entries.Gallery')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.',
                                                         through='taggit.TaggedItem', to='taggit.Tag',
                                                         verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
