# Generated by Django 3.0.5 on 2020-05-15 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0019_auto_20200515_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entries.EntryMod')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
