# Generated by Django 3.0.5 on 2020-05-15 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0020_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entries.Test'),
        ),
    ]
