# Generated by Django 3.0.5 on 2020-05-15 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0021_auto_20200516_0052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
