# Generated by Django 3.0.5 on 2020-07-29 17:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0020_delete_mymodel'),
        ('entries', '0023_auto_20200729_1813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntryArticle',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='CategoriesMods',
            new_name='ArticleCategory',
        ),
        migrations.RenameModel(
            old_name='EntryFaq',
            new_name='Faq',
        ),
        migrations.RenameModel(
            old_name='CategoriesImages',
            new_name='FaqCategory',
        ),
        migrations.RenameModel(
            old_name='EntryFile',
            new_name='File',
        ),
        migrations.RenameModel(
            old_name='CategoriesFaq',
            new_name='FileCategory',
        ),
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
        migrations.RenameModel(
            old_name='EntryGuide',
            new_name='Guide',
        ),
        migrations.RenameModel(
            old_name='EntryImageGallery',
            new_name='ImageGallery',
        ),
        migrations.RenameModel(
            old_name='CategoriesFiles',
            new_name='ImageGalleryCategory',
        ),
        migrations.RenameModel(
            old_name='EntryMod',
            new_name='Mod',
        ),
        migrations.RenameModel(
            old_name='CategoriesArticle',
            new_name='ModCategory',
        ),
        migrations.RenameModel(
            old_name='EntryNews',
            new_name='News',
        ),
        migrations.RenameModel(
            old_name='CategoriesNews',
            new_name='NewsCategory',
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'Категория статей', 'verbose_name_plural': 'Категории статей'},
        ),
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'verbose_name': 'Категория FAQ', 'verbose_name_plural': 'Категории FAQ'},
        ),
        migrations.AlterModelOptions(
            name='filecategory',
            options={'verbose_name': 'Категория файлов', 'verbose_name_plural': 'Категории файлов'},
        ),
        migrations.AlterModelOptions(
            name='imagegallerycategory',
            options={'verbose_name': 'Категория галереи', 'verbose_name_plural': 'Категории галереи'},
        ),
        migrations.AlterModelOptions(
            name='modcategory',
            options={'verbose_name': 'Категория модов', 'verbose_name_plural': 'Категории модов'},
        ),
    ]
