# Generated by Django 3.0.5 on 2020-07-29 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0024_auto_20200729_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='entries.ArticleCategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entries.FaqCategory',
                                    verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='file',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='entries.FileCategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='entries.ImageGalleryCategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entries.ModCategory',
                                    verbose_name='Категория модов'),
        ),
    ]
