# Generated by Django 3.0.5 on 2020-08-01 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0025_auto_20200729_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='datetime',
            new_name='publ_datetime',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='datetime',
            new_name='publ_datetime',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='datetime',
            new_name='publ_datetime',
        ),
        migrations.RenameField(
            model_name='imagegallery',
            old_name='datetime',
            new_name='publ_datetime',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='datetime',
            new_name='publ_datetime',
        ),
    ]
